### ISSUE TITLE
Skeleton tracking fails to parse with more than one user

### ISSUE THREAD

**Issue by shamlian** [personalrobotics/k2_client#6]
As written, the skeleton-tracking bridge does not work when there is more than one user in the scene. This appears to be due to a dependence on a max buffer size of 28000 characters, which is exceeded once two people are tracked. A fix will affect both the server in Kinect2ServerService.cs and in the client in startBody.cpp.

**Comment by shionlau** [comment]
I'm also having this bug. Has anyone fixed it?

**Comment by psigen** [comment]
I haven't finished the fix for the client yet yet, but I did update `k2_server` master to send using JSON without a fixed size in the `cleanup` branch.

https://github.com/personalrobotics/k2_server/blob/cleanup/Kinect2Server/Kinect2ServerService.cs#L260

We still need to update `k2_client` to match.
